version: '3.3'

networks:
  web:
    external: true
  internal:
    external: false

services:

  mariadb:
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
      volumes:
        - '/var/lib/mysql/mysql:/var/lib/mysql'
      container_name: dmariadb
      image: mariadb:latest
      networks:
        - internal
      labels:
        - traefik.enable=false

  fpm:
    volumes:
      - '/var/www/html:/var/www/html'
      - '/root/.ssh:/root/.ssh'
    container_name: dphp
    image: 'akuznetsov/fpm:v11'
    networks:
      - internal
    depends_on:
      - mariadb

  adminer:
    image: adminer:4.6.3-standalone
    container_name: dadminer
    labels:
      - traefik.backend=adminer
      - traefik.frontend.rule=Host:db-admin.primetki.ru
      - traefik.docker.network=web
      - traefik.port=8080
    networks:
      - internal
      - web
    depends_on:
      - mariadb

  nginx:
    volumes:
      - '/etc/nginx/site_enabled:/etc/nginx/conf.d'
      - '/var/www/html:/var/www/html'
    labels:
     - traefik.backend=nginx
     - traefik.frontend.rule=Host:primetki.ru
     - traefik.docker.network=web
     - traefik.port=80
    networks:
     - internal
     - web
    container_name: dnginx
    image: nginx:latest
    depends_on:
     - fpm
